openapi: 3.0.3
info:
  title: Shop Service API
  description:  Laba po SOA V1215 by Shalya and Lebedev
  version: 1.0.0
  
servers:
  - url: 'https://localhost:8081/api'
tags:
  - name: shop
    description: Дополнительные методы для работы с коллекцией машин
paths:
  /shop/search/by-number-of-wheels/{from}/{to}:
    get:
      tags:
        - shop
      summary: найти все транспортные средства с числом колёс в заданном диапазоне.
      operationId: getVeichlesByNumberOfWheels
      parameters:
        - name: from
          in: path
          description: Минимальное количество колес включая это число
          required: true
          schema:
            type: integer
            format: int32
        - name: to
          in: path
          description: Максимальное количество колес включая это число
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Операция выполнена успешно
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Vehicle'
        '400':
          description: Неправильно указаны параметры from и to
        '404':
          description: Машин с указанным количеством колес не найдено
        
  /shop/fix-distance/{vehicle-id}:
    put:
      tags:
        - shop
      summary: скрутить счётчик пробега транспортного средства с заданным id до нуля.
      description: Скручивает пробег, то есть ставит координаты машины с заданным id в нулевое значение.
      operationId: fixDistance
      parameters:
        - name: vehicle-id
          in: path
          description: ID машины у которой надо скрутить пробег
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Операция выполнена успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '400':
          description: Некорректно указан параметр vehicle-id
        '404':
          description: Машины с указанным vehicle-id не найдено
          
  

components:
  schemas:
    Coordinates:
      type: object
      properties:
        x:
          type: number
          format: double
          example: 56.42
        y:
          type: integer
          format: int64
          example: 666
      xml:
        name: category
    
    Vehicle:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
          
        name:
          type: string
          example: BMW X6
          nullable: false
          
        creationDate:
          type: string
          format: date
          example: 21.03.2021
          nullable: false
          
        wheelsNumber:
          type: integer
          format: int32
          example: 4
          minimum: 0
          
        mileage:
          type: integer
          format: int32
          example: 14000
          minimum: 0
          
        enginePower:
          type: integer
          format: int32
          minimum: 0
          exclusiveMinimum: true
          nullable: false
          
        fuelConsumption:
          type: number
          format: double
          minimum: 0
          exclusiveMinimum: true
          nullable: true
          
        coordinates:
          $ref: '#/components/schemas/Coordinates'
          
        vehicleType:
          type: string
          nullable: true
          enum:
            - CAR
            - PLANE
            - HELICOPTER
            - SUBMARINE
            - SHIP
            
        fuelType:
          type: string
          nullable: false
          enum:
            - KEROSENE
            - ELECTRICITY
            - PLASMA
            - ANTIMATTER
            
    VehicleToModify:
      type: object
      properties:
        name:
          type: string
          example: BMW X6
          nullable: false
          
        wheelsNumber:
          type: integer
          format: int32
          example: 4
          minimum: 0
          
        mileage:
          type: integer
          format: int32
          example: 14000
          minimum: 0
          
        enginePower:
          type: integer
          format: int32
          minimum: 0
          exclusiveMinimum: true
          nullable: false
          
        fuelConsumption:
          type: number
          format: double
          minimum: 0
          exclusiveMinimum: true
          nullable: true
          
        coordinates:
          $ref: '#/components/schemas/Coordinates'
          
        vehicleType:
          type: string
          nullable: true
          enum:
            - CAR
            - PLANE
            - HELICOPTER
            - SUBMARINE
            - SHIP
            
        fuelType:
          type: string
          nullable: false
          enum:
            - KEROSENE
            - ELECTRICITY
            - PLASMA
            - ANTIMATTER
      xml:
        name: pet
